Tasks = []
GoalCounter = 3
TaskCounter = 0

[[Goals]]
Name = 'skibidi'
Index = 0
GoalType = 0
Elements = []

[Goals.Tally]
Max = 0
Progress = 0

[[Goals]]
Name = 'gyat'
Index = 2
GoalType = 0
Elements = []

[Goals.Tally]
Max = 0
Progress = 0
