[[Goals]]
Name = 'skibidi'
GoalType = 0
Elements = []

[Goals.Tally]
Max = 10
Progress = 0

[[Goals]]
Name = ''
GoalType = 0
Elements = []

[Goals.Tally]
Max = 0
Progress = 0

[[Goals]]
Name = ''
GoalType = 0
Elements = []

[Goals.Tally]
Max = 0
Progress = 0

[[Goals]]
Name = 'test'
GoalType = 0
Elements = []

[Goals.Tally]
Max = 0
Progress = 0

[[Goals]]
Name = 'test'
GoalType = 2
Elements = []

[Goals.Tally]
Max = 0
Progress = 0

[[Tasks]]
Name = 'gyat'

[[Tasks]]
Name = 'test'

[[Tasks]]
Name = 'toilet'
